instaqolam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls')),
    path('', include('members.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, PostLikeView, PostCommentView , PostTagListView 

urlpatterns = [
    path('', PostListView.as_view(), name='index'),
    path('new/', PostCreateView.as_view(), name='new_post'),
    path('p/<uuid:pk>/', PostDetailView.as_view(), name='details'),
    path('p/<uuid:pk>/like', PostLikeView, name='like'),
    path('p/<uuid:pk>/comment', PostCommentView, name='comment'),
    path('p/<uuid:pk>/edit', PostUpdateView.as_view(), name='update_post'),
    path('p/<uuid:pk>/delete', PostDeleteView.as_view(), name='delete_post'),
    path('p/tag/<str:tag>', PostTagListView.as_view(), name='tag'),
]

posts/models.py
from typing import OrderedDict
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from datetime import datetime
import uuid

from members.storage import OverwriteStorage

from taggit.managers import TaggableManager
from taggit.models import GenericUUIDTaggedItemBase, TaggedItemBase

User = settings.AUTH_USER_MODEL


def get_upload_path(instance, filename):
    """Returns {instance.unique_id}/logo.{file_extension}"""

    extension = filename.split('.')[-1]
    return f'{instance.unique_id}/logo.{extension}'


class UUIDTaggedItem(GenericUUIDTaggedItemBase, TaggedItemBase):
    """A class for models that use UUID as pk for django.taggit"""

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")
    

class Post(models.Model):
    """A basic post model that uses UUID(unique_id) as its pk and has the fields: unique_id, title, body, author, logo, pub_date, likes and tags
    A placeholder is not created when logo field is empty, Therefore it's recommended to create a static placeholder file"""

    unique_id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    title = models.CharField(max_length=75)
    body = models.TextField()
    author = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    logo = models.ImageField(upload_to=get_upload_path, blank=True, storage=OverwriteStorage)
    pub_date = models.DateTimeField(default=datetime.now)
    likes = models.ManyToManyField(User, related_name='blogpost_like')
    tags = TaggableManager(through=UUIDTaggedItem, blank=True)

    def number_of_likes(self):
        return self.likes.count()


    def __str__(self):
        return str(self.author) + ' | ' + self.title

    def get_absolute_url(self):
        return reverse('details', args=((self.pk,)))

    
class Comment(models.Model):
    """A basic comment model that has the fields: post, user, body and pub_date
    you can change the user's model to EmailField or CharField if you want non-authorizes users to be able to comment"""
    
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    pub_date = models.DateTimeField(default=datetime.now)

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return f"{str(self.user)} | on: {self.post.title[:20]}(by {self.post.author}) | {self.body[:20]}"

posts/forms.py
from django import forms

from .models import Post, Comment

from taggit import forms as tforms

class PostForm(forms.ModelForm):
    """A form for Post model which excludes the author field
    The author field will automatically be added in PostCreateView"""

    class Meta:
        model = Post
        fields = ('title', 'body', 'logo', 'tags')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control bg-dark border border-secondary text-light'}),
            'body': forms.Textarea(attrs={'class': 'form-control bg-dark border border-secondary text-light'}),
            'logo': forms.ClearableFileInput(attrs={'class': 'form-control bg-dark border border-secondary text-light'}),
            'tags': tforms.TagWidget(attrs={'class': 'form-control bg-dark border border-secondary text-light'}),
        }


class CommentForm(forms.ModelForm):
    """A form for Comment model which only has a body field
    Comment user and post fields will automatically be defined in PostCommentView"""
    
    class Meta:
        model = Comment
        fields = ('body',)

posts/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect

from .models import Post
from .forms import PostForm, CommentForm


class PostListView(ListView):
    """Basic ListView for Post model which is order by first pub_date and then pk"""
    model = Post
    template_name = 'posts/index.html'
    ordering = ['-pub_date', '-pk']


def PostLikeView(request, pk):
    """A function-based view for liking a post, won't work if the user isn't authenticated"""
    post = get_object_or_404(Post, unique_id=request.POST.get('blogpost_id'))
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)

    return HttpResponseRedirect(reverse('details', args=[str(pk)]))


def PostCommentView(request, pk):
    """A function-based view for commentin on a post, won't work if the user isn't authenticated"""

    print(request.POST)
    post = get_object_or_404(Post, unique_id=request.POST.get('blogpost_id'))
    data = request.POST.copy()
    if request.method == 'POST':
        comment_form = CommentForm(data=data)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    print(data)

    return HttpResponseRedirect(reverse('details', args=[str(pk)]))


class PostDetailView(DetailView):
    """Basic DetailView for Post model, the amount of likes are added to the context in get_context_data
    User authorization is required to see the like button and the comment section, if not authenticated, nothing will be shown instead"""

    model = Post
    template_name = 'posts/details.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        likes_connected = get_object_or_404(Post, unique_id=self.kwargs['pk'])
        liked = False
        if likes_connected.likes.filter(id=self.request.user.id).exists():
            liked = True

        data['number_of_likes'] = likes_connected.number_of_likes() # Adding number of likes to the context so it will be shown on the template
        data['post_is_liked'] = liked # Adding status of the post being liked by the user to the context
        return data


class PostCreateView(LoginRequiredMixin, CreateView):
    """Basic CreateView for Post model which requires user authentication(LoginRequiredMixin)"""

    login_url = 'login' # Change to ur preferable login url name
    model = Post
    form_class = PostForm
    template_name = "posts/new_post.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user # Setting the post author to the request user
        self.object.save()
        form.save_m2m() # Required for django-taggit to save the tags
        return HttpResponseRedirect(self.get_success_url())


class PostUpdateView(UpdateView):
    """Basic UpdateView for Post model which requires user authentication and the request user must be the same as the post autor"""

    model = Post
    form_class = PostForm
    template_name = "posts/update_post.html"

    def dispatch(self, request, *args, **kwargs):
        """Checks if the request user is authenticated and is also the author if the post"""

        post = self.get_object()
        if request.user.is_authenticated and post.author == self.request.user:
            return super(PostUpdateView, self).dispatch(request, *args, **kwargs)
        else:
            return redirect(post) # Redirect to post's details page (Post model's get_absolute_url)

    def get_success_url(self):
        return reverse_lazy('details', args=(self.object.pk,)) # Redirect to post's details page after success


class PostDeleteView(DeleteView):
    """Basic DeleteView for Post model which requires user authentication and the request user must be the same as the post autor"""

    model = Post
    template_name = "posts/delete_post.html"
    success_url = reverse_lazy('index')

    def dispatch(self, request, *args, **kwargs):
        """Checks if the request user is authenticated and is also the author if the post"""
        post = self.get_object()
        if request.user.is_authenticated and post.author == self.request.user:
            return super(PostDeleteView, self).dispatch(request, *args, **kwargs)
        else:
            return redirect(post) # Redirect to post's details page (Post model's get_absolute_url)
        
    def get_success_url(self):
        return reverse_lazy('details', args=(self.object.pk,)) # Redirect to post's details page after success


class PostTagListView(ListView):
    """Basic ListView for Post's with a certaing tag"""
    model = Post
    template_name = "posts/tag_view.html"
    ordering = ['-pub_date', '-pk']

    def get_queryset(self):
        queryset = super(PostTagListView, self).get_queryset()
        tag = self.kwargs['tag']
        print(tag)
        queryset = queryset.filter(tags__name=tag).distinct() # Filter posts with the tag in URL's parameter
        return queryset

posts/templates/posts/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    Instaqolam ·

    {% block title %}

    {% endblock title %}
  </title>
  <link rel="stylesheet" href="{% static 'stylesheet/main.css' %}">
  <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
  <link rel="shortcut icon" href="{% static 'instaqolam.png' %}">
</head>

<body class="text-white" style="background-color: #15171a;">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">
        <img src="{% static 'instaqolam.png' %}" alt="" width="30" height="30" class="d-inline-block align-text-top">
        Instaqolam
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
          </li>

          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'new_post' %}">New post</a>
          </li>
          {% endif %}
        </ul>

        <hr>

        <ul class="navbar-nav">

          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              {{ user.username }}
            </a>
            <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end bg-dark" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'profile' user.slug %}">Profile</a></li>
              <li><a class="dropdown-item" href="{% url 'edit_account' user.slug %}">Account</a></li>
              <li>
                <hr class="dropdown-divider border-top border-secondary">
              </li>
              <li><a class="dropdown-item text-danger" href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
            </ul>
          </li>

          {% else %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              Login
            </a>
            <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end bg-dark" aria-labelledby="navbarDropdown">
              <div class="form-group">
                <form method="POST" , enctype="multipart/form-data" action="{% url 'login' %}?next={{ request.path }}">
                  {% csrf_token %}
                  <li><input type="text" name="username" placeholder="Username"
                      class="form-control bg-dark border-0 text-light shadow-none"></li>
                  <li><input type="password" name="password" placeholder="Password"
                      class="form-control bg-dark border-0 text-light shadow-none"></li>
                  <li>
                    <hr class="dropdown-divider border-top border-secondary">
                  </li>
                  <li class="dropdown-item d-inline-block" id="disabledDropdownItem">
                    <button class="btn btn-secondary border-0">Login</button>
                    <a href="{% url 'signup' %}" class="btn btn-primary border-0">Register</a>
                  </li>
                </form>
              </div>
            </ul>
          </li>

          {% endif %}

        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}

    {% endblock content %}
  </div>

</body>

</html>

posts/templates/posts/delete_post.html
{% extends 'posts/base.html' %}

{% load static %}

{% block title %}
    {{ post.title }}
{% endblock title %}


{% block content %}
    <br>
    <h1>
        <img src="
            
            {% if post.logo %}
                {{ post.logo.url }}
            {% else %}
                {% static 'posts/placeholder.png' %}
            {% endif %}
                
            " alt="" style="height: 85px; width: 85px; object-fit: cover;" class="rounded d-inline-block align-text-middle">
        {{ post.title }}
    </h1>
    <small class="text-secondary">
        {{ post.pub_date }}
    </small>
    <hr>
    <p class="text-break">
        {{ post.body|safe|linebreaks }}
    </p>
    <br>
    <hr>
    <br>
    <form method="POST", enctype="multipart/form-data">
        {% csrf_token %}
        <button class="btn btn-outline-danger">Delete</button>
        <a href="{% url 'index' %}" class="btn btn-secondary border border-secondary">Back</a>
    </form>
{% endblock content %}
    

posts/templates/posts/details.html
{% extends 'posts/base.html' %}

{% load static %}

{% block title %}
{{ post.title }}
{% endblock title %}


{% block content %}
<br>
<h1>
    <img src="
            
            {% if post.logo %}
                {{ post.logo.url }}
            {% else %}
                {% static 'posts/placeholder.png' %}
            {% endif %}
                
            " alt="" style="height: 85px; width: 85px; object-fit: cover;"
        class="rounded d-inline-block align-text-middle">
    {{ post.title }}
</h1>
<small class="text-secondary">
    {{ post.pub_date }} by <a href="{% url 'profile' post.author.profile.slug %}"
        class="text-decoration-none text-info">-{{ post.author }}</a>


    {% if user == post.author %}
    <a class="text-light" data-bs-toggle="dropdown" aria-expanded="false">
        <svg width="12" height="19" fill="currentColor" class="bi bi-three-dots-vertical" viewBox="0 0 16 16">
            <path
                d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
        </svg></a>
    <ul id="moreContentDropdown" class="dropdown-menu dropdown-menu-dark bg-dark">

        <li><a id="dropdownTopItem" class="dropdown-item text-light text-center"
                href="{% url 'update_post' post.pk %}">edit</a></li>
        <li><a id="dropdownBottomItem" class="dropdown-item text-danger text-center"
                href="{% url 'delete_post' post.pk %}">delete</a></li>
    </ul>
    {% endif %}

    {% if user.is_authenticated %}
    <form action="{% url 'like' post.pk %}" method="POST" class="d-inline-block">
        {% csrf_token %}

        {% if post_is_liked %}
        
        <label style="cursor: pointer;">
            <button type="submit" name="blogpost_id" value="{{post.pk}}" class="btn btn-info"
                style="display: none;"></button>
            <svg width="16" height="16" fill="white" class="bi bi-suit-heart-fill" viewBox="0 0 16 16">
                <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
                </svg></a>
        </label>
        {% else %}

        <label style="cursor: pointer;">
            <button type="submit" name="blogpost_id" value="{{post.pk}}" class="btn btn-info"
                style="display: none;"></button>
            <svg width="16" height="16" fill="white" class="bi bi-suit-heart" viewBox="0 0 16 16">
                <path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"/>
                </svg></a>

        </label>
        {% endif %}
    </form>
    {% endif %}
    <span class="text-light">{{ number_of_likes }} Like{{ number_of_likes|pluralize }}</span>


</small>
<hr>
<p class="text-break">
    {{ post.body|safe|linebreaks }}
</p>
<br>
<small>
{% for tag in post.tags.all %}
<a href="{% url 'tag' tag %}" class="text-decoration-none text-info">#{{ tag }}</a>
{% endfor %}
</small>
<hr>
<br>


{% if user.is_authenticated %}
<form method="POST" action="{% url 'comment' post.pk %}" enctype="multipart/form-data">
    {% csrf_token %}
    <textarea placeholder="Comment" name="body" id="id_body" cols="30" rows="6" class="d-inline-block form-control bg-dark border border-secondary text-light" style="width: 25%;" required></textarea>
    <button name="blogpost_id" value="{{post.pk}}" class="btn btn-dark border border-secondary" style="margin-bottom: 20px;">Post</button>
</form>
    
{% endif %}

{% for comment in post.comments.all %}
<div>
    <a href="{% url 'profile' comment.user.profile.slug %}"><img src="

        {% if comment.user.profile.profile_picture %}
            {{ comment.user.profile.profile_picture.url }}
        {% else %}
            {% static 'members/placeholder.png' %}
        {% endif %}
            
        " alt="" style="height: 25px; width: 25px; object-fit: cover;" class="rounded-circle d-inline-block align-text-center"></a>
    <a href="{% url 'profile' comment.user.profile.slug %}" class="text-decoration-none text-info d-inline-block">-{{ comment.user }}</a>
    <span class="text-secondary">{{ comment.pub_date.date }}</span>
    </div>
    <p style="margin-left: 30px;">{{ comment.body }}</p>
{% endfor %}
<br>
<br>
    
{% endblock content %}

posts/templates/posts/index.html
{% extends 'posts/base.html' %}

{% load static %}

{% block title %}
Home
{% endblock title %}


{% block content %}

<br>
<h1>Home</h1>

<hr>

{% if post_list %}
    <ul class="list-group border border-secondary">
    {% for post in post_list %}
        <li class="list-group-item bg-dark text-white border border-secondary">
            <a href="{% url 'details' post.pk %}"><img src="
            
            {% if post.logo %}
                {{ post.logo.url }}
            {% else %}
                {% static 'posts/placeholder.png' %}
            {% endif %}
                
            " alt="" style="height: 70px; width: 70px; object-fit: cover;" class="rounded d-inline-block align-text-bottom"></a>
            <div class="d-inline-block text-wrap">
                <a href="{% url 'details' post.pk %}" class="text-decoration-none text-light">{{ post.title }}</a>
                <br>
                <span>{{ post.body|slice:50 }}</span>
                <br>
                <small>
                    <span class="text-secondary">{{ post.pub_date.date }} by
                        <a href="{% url 'profile' post.author.profile.slug %}"><img src="
            
                            {% if post.author.profile.profile_picture %}
                                {{ post.author.profile.profile_picture.url }}
                            {% else %}
                                {% static 'members/placeholder.png' %}
                            {% endif %}
                                
                            " alt="" style="height: 25px; width: 25px; object-fit: cover;" class="rounded-circle d-inline-block align-text-center"></a>
                        <a href="{% url 'profile' post.author.profile.slug %}" class="text-decoration-none text-info d-inline-block">-{{ post.author }}</a>
                    </span>
                </small>
            </div>
        </li>
    {% endfor %}
    </ul>
    <br>
    <br>
{% else %}
    <br>
    <h3>No posts available!</h1>
{% endif %}

{% endblock content %}

posts/templates/posts/new_post.html
{% extends 'posts/base.html' %}

{% block title %}
    New Post
{% endblock title %}


{% block content %}

<br>
<h1>New post</h1>
<hr>
<div class="form-group">
<form method="POST", enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-dark border border-secondary">Post</button>
    <a href="{% url 'index' %}" class="btn btn-secondary border border-secondary">Back</a>
</form>
</div>
<br>
<br>
    
{% endblock content %}

posts/templates/posts/tag_view.html
{% extends 'posts/base.html' %}

{% load static %}

{% block title %}
{{ view.kwargs.tag }}
{% endblock title %}


{% block content %}

<br>
<h1>Tag: {{ view.kwargs.tag }}</h1>

<hr>

{% if post_list %}
    <ul class="list-group border border-secondary">
    {% for post in post_list %}
        <li class="list-group-item bg-dark text-white border border-secondary">
            <a href="{% url 'details' post.pk %}"><img src="
            
            {% if post.logo %}
                {{ post.logo.url }}
            {% else %}
                {% static 'posts/placeholder.png' %}
            {% endif %}
                
            " alt="" style="height: 70px; width: 70px; object-fit: cover;" class="rounded d-inline-block align-text-bottom"></a>
            <div class="d-inline-block text-wrap">
                <a href="{% url 'details' post.pk %}" class="text-decoration-none text-light">{{ post.title }}</a>
                <br>
                <span>{{ post.body|slice:50 }}</span>
                <br>
                <small>
                    <span class="text-secondary">{{ post.pub_date.date }} by
                        <a href=""><img src="
            
                            {% if post.author.profile.profile_picture %}
                                {{ post.author.profile.profile_picture.url }}
                            {% else %}
                                {% static 'members/placeholder.png' %}
                            {% endif %}
                                
                            " alt="" style="height: 25px; width: 25px; object-fit: cover;" class="rounded-circle d-inline-block align-text-center"></a>
                        <a href="{% url 'profile' post.author.profile.slug %}" class="text-decoration-none text-info d-inline-block">-{{ post.author }}</a>
                    </span>
                </small>
            </div>
        </li>
    {% endfor %}
    </ul>
    <br>
    <br>
{% else %}
    <br>
    <h3>No posts available!</h1>
{% endif %}

{% endblock content %}

posts/templates/posts/update_post.html
{% extends 'posts/base.html' %}

{% block title %}
    Editing {{ post.title }}
{% endblock title %}


{% block content %}

<br>
<h1>Edit Post</h1>
<hr>
<div class="form-group">
<form method="POST", enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-dark border border-secondary">Apply</button>
    <a href="{% url 'index' %}" class="btn btn-secondary border border-secondary">Back</a>
</form>
</div>
<br>
<br>
    
{% endblock content %}